title: Restock Rocket
author: Restock Rocket
email: support@restockrocket.io
description: >
  With Restock Rocket, add a 'Notify me when available' button to your store & allow customers to subscribe for back in stock + restock alerts to any out of stock product. When you restock, they will instantly receive an email or SMS alert informing them to make a purchase before stock runs out!
image: '/assets/img/Banner.png'
baseurl: ''
url: 'https://restockrocket.io'
header_pages:
  - index.md
  - help.md
footer_links:
  privacy:
    link: /policy.html
    title: Privacy Policy
  terms:
    link: /terms.html
    title: Terms & Conditions
defaults:
    - scope:
        path: "assets/img"
      values:
        image: true
theme: minima
plugins:
    - jekyll-seo-tag
    - jekyll-sitemap
